### ISSUE TITLE
[ERR] Error when load plugin (PreloadAlert.dll): System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jgriff72** [Queuete/PreloadAlert#9]
2021-06-06 09:41:11.616 -04:00 [ERR] Error when load plugin (PreloadAlert.dll): System.NullReferenceException: Object reference not set to an instance of an object.
   at ExileCore.Shared.Nodes.ColorNodeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /buddy/exileapi/Core/Shared/Nodes/ColorNodeConverter.cs:line 20
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ExileCore.BaseSettingsPlugin`1._LoadSettings() in /buddy/exileapi/Core/BaseSettingsPlugin.cs:line 51
   at ExileCore.Shared.PluginAutoUpdate.PluginLoader.TryLoadPlugin(Assembly assembly, DirectoryInfo directoryInfo) in /buddy/exileapi/Core/Shared/PluginAutoUpdate/PluginLoader.cs:line 115)

**Comment by jgriff72** [comment]
*Update**  The only workaround i've found that works is to delete PreloadAlert_settings.json in the ../config/global/ folder each time i restart the hud.

**Comment by git42leech** [comment]
Could be the new Newtonsoft lib, should be recompiled.
